name: Build Workflow

on: [push, pull_request]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH
    - name: Install dependencies and build
      run: |
        bun install
        bun run build
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: dist
        path: dist/

  build_backend:
    needs: build_frontend
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Download artifact
      uses: actions/download-artifact@v4.1.0
      with:
        name: dist
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install Tauri CLI
      run: cargo install tauri-cli
    - name: Build backend
      run: cargo tauri build'
