name: Build Workflow

on: [push, pull_request]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.1
    - name: Install dependencies and build
      run: |
        bun install
        bun run build
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: dist
        path: dist/

  build_backend:
    needs: build_frontend
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Download artifact
      uses: actions/download-artifact@v4.1.0
      with:
        name: dist
        path: dist/
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install Tauri CLI
      run: cargo install tauri-cli
    - name: Build backend
      run: cargo tauri build
        - name: Get latest release
      id: latest_release
      run: |
        LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/Alixxx-please/SimpliciText/releases/latest" | jq -r .tag_name)
        echo "::set-output name=version::${LATEST_RELEASE}"
    - name: Executables artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: executables
        path: D:\a\SimpliciText\SimpliciText\src-tauri\target\release\bundle\msi\SimpliciText_${{ steps.latest_release.outputs.version }}_x64_en-US.msi